<a href="https://colab.research.google.com/github/Kanchanajaddu/MLassignments/blob/main/MLassignmentq1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Given question:

#A company wants to predict employee productivity scores to improve workforce planning and training programs.
#You are hired as a Data Scientist to build a multivariate linear regression model
#that predicts an employee’s Productivity Score based on multiple work-related factors.
#Experience (yrs), Training Hours, Working Hours, Projects, Productivity Score
2,40,38,3,62
5,60,42,6,78
1,20,35,2,55
8,80,45,8,88
4,50,40,5,72
10,90,48,9,92
3,30,37,4,65
6,70,44,7,82
7,75,46,7,85
2,25,36,3,60
#Interpretation
#Which factor most strongly impacts productivity?
#How does training affect productivity?
#Should the company increase training hours or working hours?
#What happens if Working Hours increase beyond optimal limits?
#Can productivity ever decrease with more experience?
#How would you detect overfitting in this model?
#Suggest one new feature to improve prediction accuracy.

In [ ]:
##loading the data
data={'Experience (yrs)':[2, 5, 1, 8, 4, 10, 3, 6, 7, 2],
      'Training Hours':[40, 60, 20, 80, 50, 90, 30, 70, 75, 25],
      'Working Hours':[38, 42, 35, 45, 40, 48, 37, 44, 46, 36],
      'Projects':[3, 6, 2, 8, 5, 9, 4, 7, 7, 3],
      'Productivity Score':[62, 78, 55, 88, 72, 92, 65, 82, 85, 60]
      }

In [ ]:
data

{'Experience (yrs)': [2, 5, 1, 8, 4, 10, 3, 6, 7, 2],
 'Training Hours': [40, 60, 20, 80, 50, 90, 30, 70, 75, 25],
 'Working Hours': [38, 42, 35, 45, 40, 48, 37, 44, 46, 36],
 'Projects': [3, 6, 2, 8, 5, 9, 4, 7, 7, 3],
 'Productivity Score': [62, 78, 55, 88, 72, 92, 65, 82, 85, 60]}

In [ ]:
#converting the data into dataframe
import pandas as pd
df=pd.DataFrame(data)

In [ ]:
#printing the dataframe
df

,Experience (yrs),Training Hours,Working Hours,Projects,Productivity Score
0,2,40,38,3,62
1,5,60,42,6,78
2,1,20,35,2,55
3,8,80,45,8,88
4,4,50,40,5,72
5,10,90,48,9,92
6,3,30,37,4,65
7,6,70,44,7,82
8,7,75,46,7,85
9,2,25,36,3,60

In [ ]:
#printing the first five rows
df.head()

,Experience (yrs),Training Hours,Working Hours,Projects,Productivity Score
0,2,40,38,3,62
1,5,60,42,6,78
2,1,20,35,2,55
3,8,80,45,8,88
4,4,50,40,5,72

In [ ]:
#define features (x)[independent variables] and target (y)[dependent variables]
x=df[['Experience (yrs)', 'Training Hours', 'Working Hours', 'Projects']]
y=df['Productivity Score']

In [ ]:
#splitting the data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(f"training set size:{len(x_train)} samples")
print(f"testing set size:{len(x_test)} samples")

training set size:8 samples
testing set size:2 samples

In [ ]:
#build and train the multivariate linear regression model
from sklearn.linear_model import LinearRegression
#initialise the regression model
model=LinearRegression()
#train the model using the training data
model.fit(x_train,y_train)
print("model trained successfully")

model trained successfully

In [ ]:
#evaluate the model
#regression models can be evaluated by using MAE,MSE,R2 score to find the diff of actual and predicted values
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
#make predictions on  the test set
y_pred=model.predict(x_test)
#MEAN ABSOLUTE ERROR
mae=mean_absolute_error(y_test,y_pred)
#MEAN SQUARED ERROR
mse=mean_squared_error(y_test,y_pred)
#ROOT MEAN SQUARE ERROR
rmse=mse**0.5
#R2_SCORE
r2=r2_score(y_test,y_pred)
print(f"Mean Absolute Error:{mae}")
print(f"Mean Squared Error:{mse}")
print(f"Root Mean Squared Error:{rmse}")
print(f"R2_score:{r2}")

Mean Absolute Error:0.46656905807710913
Mean Squared Error:0.30116227582834026
Root Mean Squared Error:0.5487825396533131
R2_score:0.9879535089668664

In [ ]:
#interpret the model coefficients
coefficients=pd.DataFrame({'Feature':x.columns,'Coefficient':model.coef_})
print("model coefficients")
display(coefficients)
print(f"Intercept:{model.intercept_}")

model coefficients

            Feature  Coefficient
0  Experience (yrs)    -0.878965
1    Training Hours     0.085896
2     Working Hours     0.716935
3          Projects     4.265983

Intercept:21.03611517813573

In [ ]:
#Which factor most strongly impacts productivity?
#How does training affect productivity?
#Should the company increase training hours or working hours?
#What happens if Working Hours increase beyond optimal limits?
#Can productivity ever decrease with more experience?
#How would you detect overfitting in this model?
#Suggest one new feature to improve prediction accuracy.